config/routes.rb
Rails.application.routes.draw do
  root 'techniques#index'
  resources :techniques
  resources :types
  resources :positions
  resources :notes
  get "pages/:page" => "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/technique.rb
class Technique < ApplicationRecord
  belongs_to :position
  belongs_to :type
  has_many :note
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  before_action :set_technique, only: [:show, :edit, :update, :destroy]

  # GET /techniques
  # GET /techniques.json
  def index
    @techniques = Technique.all
  end

  # GET /techniques/1
  # GET /techniques/1.json
  def show
  end

  # GET /techniques/new
  def new
    @technique = Technique.new
  end

  # GET /techniques/1/edit
  def edit
  end

  # POST /techniques
  # POST /techniques.json
  def create
    @technique = Technique.new(technique_params)

    respond_to do |format|
      if @technique.save
        format.html { redirect_to @technique, notice: 'Technique was successfully created.' }
        format.json { render :show, status: :created, location: @technique }
      else
        format.html { render :new }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techniques/1
  # PATCH/PUT /techniques/1.json
  def update
    respond_to do |format|
      if @technique.update(technique_params)
        format.html { redirect_to @technique, notice: 'Technique was successfully updated.' }
        format.json { render :show, status: :ok, location: @technique }
      else
        format.html { render :edit }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techniques/1
  # DELETE /techniques/1.json
  def destroy
    @technique.destroy
    respond_to do |format|
      format.html { redirect_to techniques_url, notice: 'Technique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technique
      @technique = Technique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technique_params
      params.require(:technique).permit(:name, :position_id, :type_id, :top, :gi)
    end
end

app/helpers/techniques_helper.rb
module TechniquesHelper
end

app/views/techniques/_form.html.erb
<%= form_with(model: technique, local: true) do |form| %>
  <% if technique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technique.errors.count, "error") %> prohibited this technique from being saved:</h2>

      <ul>
      <% technique.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position_id %>
    <%= form.text_field :position_id %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.text_field :type_id %>
  </div>

  <div class="field">
    <%= form.label :top %>
    <%= form.check_box :top %>
  </div>

  <div class="field">
    <%= form.label :gi %>
    <%= form.check_box :gi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/techniques/edit.html.erb
<h1>Editing Technique</h1>

<%= render 'form', technique: @technique %>

<%= link_to 'Show', @technique %> |
<%= link_to 'Back', techniques_path %>

app/views/techniques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Techniques</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Type</th>
      <th>Top</th>
      <th>Gi</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @techniques.each do |technique| %>
      <tr>
        <td><%= technique.name %></td>
        <td><%= technique.position %></td>
        <td><%= technique.type %></td>
        <td><%= technique.top %></td>
        <td><%= technique.gi %></td>
        <td><%= link_to 'Show', technique %></td>
        <td><%= link_to 'Edit', edit_technique_path(technique) %></td>
        <td><%= link_to 'Destroy', technique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technique', new_technique_path %>

app/views/techniques/new.html.erb
<h1>New Technique</h1>

<%= render 'form', technique: @technique %>

<%= link_to 'Back', techniques_path %>

app/views/techniques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technique.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @technique.position %>
</p>

<p>
  <strong>Type:</strong>
  <%= @technique.type %>
</p>

<p>
  <strong>Top:</strong>
  <%= @technique.top %>
</p>

<p>
  <strong>Gi:</strong>
  <%= @technique.gi %>
</p>

<%= link_to 'Edit', edit_technique_path(@technique) %> |
<%= link_to 'Back', techniques_path %>